// <auto-generated />
namespace yostocksApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class YoustockUserIEnumerable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YoustockUserIEnumerable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806131515405_YoustockUser-IEnumerable2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
