// <auto-generated />
namespace yostocksApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modelchangebuyFragmentModelRequestedAmount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelchangebuyFragmentModelRequestedAmount));
        
        string IMigrationMetadata.Id
        {
            get { return "201806121203526_model-change-buyFragmentModel.RequestedAmount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
